# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0004_auto_20170219_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(help_text='Blog Post related to this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_g.BlogPost'),
        ),
    ]
