# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0006_auto_20170219_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(help_text='Select Author for this Blog Post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_g.BlogAuthor'),
        ),
    ]
