# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0007_auto_20170219_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date']},
        ),
    ]
