# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0008_auto_20170219_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(blank=True, help_text='Bio Data of Author', max_length=2000, null=True),
        ),
    ]
