# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0009_auto_20170221_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-post_date'], 'permissions': (('can_create_edit_delete_posts', 'create edit delete post'),)},
        ),
    ]
