# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0010_auto_20170224_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'permissions': (('can_create_edit_delete_authors', 'create edit delete author'),)},
        ),
    ]
