# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_g', '0011_auto_20170225_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(help_text='Blog Post related to this comment', on_delete=django.db.models.deletion.CASCADE, to='blog_g.BlogPost'),
        ),
    ]
